export const MOCK_APPROVAL_CAMPAIGNS = [
  { 
    id: 'CAM-9901', 
    vendor: 'Maboneng Textiles', 
    vendorLogo: 'https://images.unsplash.com/photo-1544441893-675973e31985?auto=format&fit=crop&q=80&w=100',
    vendorDescription: 'Authentic shweshwe and contemporary Joburg tailoring.',
    influencer: 'Zanele M.', 
    influencerAvatar: 'https://i.pravatar.cc/150?u=zan',
    influencerStats: { reach: '42k', engage: '12.4%' },
    products: 'Heritage Evening Wrap', 
    type: 'Flash Sale Boost',
    duration: 'Oct 20 - Oct 30', 
    platforms: ['Instagram', 'TikTok'], 
    budget: 'R2,500', 
    commission: '15%',
    status: 'Pending', 
    submissionDate: '2024-10-15',
    mediaUrl: 'https://images.unsplash.com/photo-1549490349-8643362247b5?auto=format&fit=crop&q=80&w=800',
    notes: 'Creator will focus on a "Day in the Life" reel featuring the Wrap at Maboneng Precinct.'
  },
  { 
    id: 'CAM-9902', 
    vendor: 'Soweto Gold', 
    vendorLogo: 'https://images.unsplash.com/photo-1610492317734-d0370bcc645b?auto=format&fit=crop&q=80&w=100',
    vendorDescription: 'Handcrafted premium jewelry inspired by heritage.',
    influencer: 'Thabo K.', 
    influencerAvatar: 'https://i.pravatar.cc/150?u=tha',
    influencerStats: { reach: '85k', engage: '5.2%' },
    products: 'Zebu Wallet Collection', 
    type: 'Lifestyle Integration',
    duration: 'Oct 25 - Nov 05', 
    platforms: ['TikTok', 'YouTube'], 
    budget: 'R4,800', 
    commission: '12%',
    status: 'Approved', 
    submissionDate: '2024-10-14',
    mediaUrl: 'https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&q=80&w=800',
    notes: 'Unboxing focus with emphasis on the leather grain and artisan stamping process.'
  },
  { 
    id: 'CAM-9903', 
    vendor: 'Rosebank Art Gallery', 
    vendorLogo: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?auto=format&fit=crop&q=80&w=100',
    vendorDescription: 'Modern Joburg fine art and sculptures.',
    influencer: 'Lerato D.', 
    influencerAvatar: 'https://i.pravatar.cc/150?u=ler',
    influencerStats: { reach: '15k', engage: '18.1%' },
    products: 'Ceramic Table Set', 
    type: 'Interior Design Niche',
    duration: 'Oct 15 - Oct 22', 
    platforms: ['Instagram'], 
    budget: 'R1,200', 
    commission: '20%',
    status: 'Pending', 
    submissionDate: '2024-10-16',
    mediaUrl: 'https://images.unsplash.com/photo-1611486212330-9199b0c0bc3f?auto=format&fit=crop&q=80&w=800',
    notes: 'Interior styling reel showing the ceramics in a contemporary Gauteng loft setting.'
  },
  { 
    id: 'CAM-9904', 
    vendor: 'Jozi Apothecary', 
    vendorLogo: 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?auto=format&fit=crop&q=80&w=100',
    vendorDescription: 'Botanical skincare inspired by African flora.',
    influencer: 'Nomsa G.', 
    influencerAvatar: 'https://i.pravatar.cc/150?u=nom',
    influencerStats: { reach: '22k', engage: '8.4%' },
    products: 'Marula Glow Pack', 
    type: 'Product Review',
    duration: 'Oct 10 - Oct 20', 
    platforms: ['YouTube', 'Instagram', 'Facebook'], 
    budget: 'R2,100', 
    commission: '10%',
    status: 'Rejected', 
    submissionDate: '2024-10-08',
    mediaUrl: 'https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?auto=format&fit=crop&q=80&w=800',
    notes: 'Full skincare routine featuring the Marula oil. (Rejected due to low-res media asset).'
  }
];